### ISSUE TITLE
Getting TokenMismatchException on /register 

### ISSUE THREAD

**Issue by yadakhov** [rydurham/L4withSentry#72]
Illuminate \ Session \ TokenMismatchException

Installed a clean installation and can't seem to get it working with /register

Is anyone else getting the same error?

**Comment by rydurham** [comment]
I was not able to reproduce this issue, however I have just made some adjustments to the CSRF filter (to fix the recent laravel security vulnerability), which might be helpful to your problem.   If not, see if you can determine if the problem is due to an actual token mismatch, or if it is being caused by the token not being submitted at all with the registration form.

**Comment by yadakhov** [comment]
Thanks.  Seem to be working.
