### ISSUE TITLE
Could not scan for classes inside "app/libraries" which does not appear to be a file nor a folder

### ISSUE THREAD

**Issue by samuel4x4** [rydurham/L4withSentry#8]
After php composer.phar install" you'll receive this error:

[RuntimeException]
Could not scan for classes inside "app/libraries" which does not appear to be a file nor a folder

I removed "app/libraries" from composer.json and it works.

**Comment by rydurham** [comment]
Good catch!  This has now been fixed.

**Comment by samuel4x4** [comment]
cool, thanks ;)

**Comment by varmad** [comment]
Still am getting the same

**Comment by jimthedev** [comment]
Ryan, looking at .gitignore, it appears that you don't have an app/libraries directory, so maybe the best option is to just remove this reference from composer.json for now. Also, I added a phpunit blacklist for vendor/ since when we run our tests, we don't want to test all of our bundles' php files.

**Comment by rydurham** [comment]
The 'app/libraries' reference was a holdover from my original implementation.  Good catch!

**Comment by jimthedev** [comment]
Awesome. Thanks for merging Ryan!

**Comment by work-priyank** [comment]
Thanks! It helped!
